const router = require('express').Router();
const { nearbyPlaces } = require('../services/mapsService');
const { currentWeather, currentCityWeather } = require('../services/weatherService');
const { synthesize } = require('../services/ttsService');
const { generateDayPlan } = require('../services/itineraryService');

router.get('/health', async (req, res) => {
  res.json({ status: 'ok', runtime: 'node' });
});

router.post('/itinerary', async (req, res, next) => {
  try {
    const items = generateDayPlan(req.body?.interests || []);
    res.json({ day_plan: items, rationale: 'Plan generated by Node heuristics.' });
  } catch (e) { next(e); }
});

router.post('/nearby', async (req, res, next) => {
  try {
    const { lat, lng, radius_m = 1500, types = ['restaurant','tourist_attraction','transit_station'] } = req.body || {};
    const raw = await nearbyPlaces(lat, lng, radius_m, types);
    const places = raw.map(r => {
      const loc = r.geometry?.location || {};
      const type = Array.isArray(r.types) && r.types.length ? r.types[0] : 'unknown';
      return {
        name: r.name || 'Unknown',
        type,
        lat: Number(loc.lat || lat),
        lng: Number(loc.lng || lng),
        rating: r.rating,
        address: r.vicinity || r.formatted_address,
      };
    });
    res.json({ places });
  } catch (e) { next(e); }
});

router.post('/tts', async (req, res, next) => {
  try {
    const { text, language , voice } = req.body || {};
    const bytes = await synthesize(text, language, voice);
    res.json({ audio_b64: Buffer.from(bytes).toString('base64'), content_type: 'audio/mpeg' });
  } catch (e) { next(e); }
});

router.post('/optimize', async (req, res, next) => {
  try {
    const items = req.body?.items || [];
    let weather_hint = null;
    const first = items[0] || {};
    if (typeof first.lat === 'number' && typeof first.lng === 'number') {
      try {
        const w = await currentWeather(first.lat, first.lng);
        if (w) {
          const cond = Array.isArray(w.weather) && w.weather[0]?.description;
          const temp = w.main?.temp;
          weather_hint = cond && temp != null ? `${cond.charAt(0).toUpperCase()}${cond.slice(1)}, ${temp}°C` : (cond || null);
        }
      } catch (_) {}
    }
    res.json({ items, weather_hint });
  } catch (e) { next(e); }
});

router.post('/weather', async (req, res, next) => {
  try {
    const { lat, lng } = req.body || {};
    if (typeof lat !== 'number' || typeof lng !== 'number') {
      return res.status(400).json({ error: 'lat and lng are required numbers' });
    }
    const w = await currentCityWeather(lat, lng);
    res.json(w);
  } catch (e) { next(e); }
});



module.exports = router;


